version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    networks:
      - my_network


  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
    depends_on:
      - zookeeper
    networks:
      - my_network

  app:
    image: 'kafka-demo:latest'
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/kafka-demo
    depends_on:
      - kafka
      - zookeeper
    links:
        - kafka:kafka
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
