version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper


  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
    depends_on:
      - zookeeper

#    app:
#      image: 'kafka-demo:latest'
#      ports:
#        - 8081:8080
#      build:
#        context: .
#      depends_on:
#        - kafka
#      links:
#        - kafka:kafka
